### PR TITLE
Support for Signed URLs

### PR DESCRIPTION
**Pull request by nerg4l**
Hi,

This is a PR for #80.

During the implementation I ran into two limitations.

1. Passing parameters to the `route` method inside the links partial is a bit tricky and I did not want to mess things up.
2. As I checked the route parameters currently not accessible from the items handler.

Feel free to correct me if I'm wrong.

### CODE REVIEW

**Comment by freekmurze** [comment]
Even though the code is working and the implementation seems fine, I've decided not to merge it in. We mostly only want to maintain and invest time in code that we use ourselves. 

Please fork our package and implement the functionality there.

Thanks for your work on this.

**Comment by ChrisHardie** [comment]
@nerg4l did you ever fork or otherwise release this feature? I have the same need. Thank you.

**Comment by nerg4l** [comment]
@ChrisHardie I played with it a bit and then decided not to. This library is great for adding simple RSS but a bit hard to extend. Moreover, it took me 10 minutes to create a protected RSS.

**Comment by ChrisHardie** [comment]
For anyone interested, I shared about how I ended up implementing this: https://tech.chrishardie.com/2021/user-private-rss-feed-laravel/

**Pull request closed without merging**
