### PR TITLE
Fix the items key in config

### PR DESCRIPTION
**Pull request by khaledw62**
change the items key to accept array instead of string to include the class name and the class method name and optional argument

### CODE REVIEW

**Comment by freekmurze** [comment]
If reverted on of the tests to the original value, and it seems to be failing.

Could you adapt the code so that it is non-breaking and will pass for each test?

**Comment by khaledw62** [comment]
i think they fails because i've changed ```DummyRepository.php``` in ```tests``` directory

**Comment by khaledw62** [comment]
ok i'll check it now

**Comment by khaledw62** [comment]
i think i should change ```Your Test``` to assert throwing ```invalid exception ```for an empty items key

**Comment by khaledw62** [comment]
Screen Shot 2021-05-17 at 4 35 50 PM

**Comment by freekmurze** [comment]
Thanks for your work on this. I've decided to keep things as they are for now. We'll make improvements on this in the next major version of the package.

**Comment by khaledw62** [comment]
okay @freekmurze let me know if you have any package or any thing needs help ,i hope to contribute with any thing has your name in it

**Pull request closed without merging**
