### PR TITLE
RSS feed type

### LINKED ISSUE #108: mix of RSS and Atom
Atm the package mixes RSS and Atom. The blade feed view renders an Atom feed but the blade link view generates RSS link tags.
https://github.com/spatie/laravel-feed/blob/732d840cfa6c0369a48fb32d136b812dc3d97ab1/resources/views/links.blade.php#L2
`type="application/atom+xml"` would be correct.

My idea would be to add a new key to the config array which contains the html link type. And if it's `!$type === true` it doesn't render this feed in the links.
This would allow to do everything the right way. I also suggest to add a RSS feed view to generate rss feeds.

### PR DESCRIPTION
**Pull request by Gummibeer**
fixes #108 

contains: #109

### CODE REVIEW

**Comment by freekmurze** [comment]
This one is breaking, right? (due to the `feed` view being renamed)

**Comment by Gummibeer** [comment]
No, I've kept the `feed` view which now only includes the `atom` view. This way it non BC and in the next major release the `feed` view could get removed.

**Comment by Gummibeer** [comment]
During next major release it could also be an idea to remove the feed type from config or make it an array to allow to render the same feed in multiple types. The route should get a suffix `.rss`, `.atom` or `.json` for the new JSON feed type.

**Comment by freekmurze** [comment]
Thanks! I think we can create a new major version when PHP 7.4 arrives. For this (and other package) the plan is to create PHP 7.4 only new major version where we can use typed properties, short closures and all the sweetness that PHP 7.4 brings to the table.

**Pull request merged**
