### PR TITLE
Blade component to include feed links

### PR DESCRIPTION
**Pull request by seschi98**
This should fix issue #147 😄

### CODE REVIEW

**Comment by freekmurze** [comment]
Nice, could you also add a test for this?

**Comment by seschi98** [comment]
> Nice, could you also add a test for this?

You mean to verify that the links are inserted in the DOM if the component is used? Sure, I'll add that :)

**Comment by seschi98** [comment]
@freekmurze I added a route that renders the blade component (with a little helper method because I think it's not nice to add a blade file to the repo) and a test that creates a snapshot of the result, just like with the other route where the file is `@include`d. Hope thats allright with you 🤔

**Comment by freekmurze** [comment]
The tests seem to be failing. Could you take a look at that?

**Comment by seschi98** [comment]
@freekmurze In some environments there was a trailing space. I don't know where that came from, but it works if you `trim()` the result. Hope that's okay with you...

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
